### ISSUE TITLE
HTML&CSS Basics: Styling with Combinators and Pseudo-Classes

### ISSUE THREAD

**Issue by codingbootcampseu** [GanyFeta/bootcamp-schedule#17]
- Add spacing between the different areas of your main content
- Add styling to the navigation links
  - Add spacing between the navigation links
  - Add a general color for the navigation links
  - Add specific styling for the `:hover` and `:active` state (i.e. different color or background color)
- Use the `border` property to draw a line over each article of the main content execept for the first one

**Hints**

The Lobotomized Owl selector `* + *` can be useful for some of the current requirements.

Specific sides of the border box can be style using the `border-top`, `border-bottom`, `border-left` or `border-right` properties.

**Example Solution and Comparison**

- [Example solution](https://codesandbox.io/s/github/coding-bootcamps-eu/lexample-cv/blob/styling-with-combinators-and-pseudo-classes/) for this task.
- [Comparison to previous task](https://github.com/coding-bootcamps-eu/lexample-cv/compare/basic-styling...styling-with-combinators-and-pseudo-classes)

**Comment by GanyFeta** [comment]
Done!
Inhalte und fine tuning folgen.
