### ISSUE TITLE
Git Intro: Clone existing CV repository from GitHub

### ISSUE THREAD

**Issue by codingbootcampseu** [GanyFeta/bootcamp-schedule#30]
> 🚨 Please be sure that you added all local changes to GitHub

- [x] Rename the existing CV folder to `cv-old`
- [x] Go to your cv repository on GitHub
- [x] Copy the clone link 
  - Use HTTPS if you haven't configured SSH yet - otherwise use SSH 💡
- [x] Clone the repository onto your computer (into your coding folder)

> 🚨 Heads up where you use the `git clone` command because it will create a new folder including a git repository

**Comment by GanyFeta** [comment]
SSH works!!!!
