### ISSUE TITLE
Setup: NVM and Node.js

### ISSUE THREAD

**Issue by codingbootcampseu** [GanyFeta/bootcamp-schedule#84]
You will now install NVM (node version manager) and Node.js. NVM is a convenient tool to manage and install Node.js on your computer. Node.js itself is a runtime that can run JavaScript code outside of browsers.

1. Open a new terminal and run the command `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash`
2. Close the terminal and open a new terminal
3. Type the command `nvm --version` and check that the version of nvm is printed in the terminal
4. You will now install the LTS version of node using the command `nvm install --lts`
5. Type the command `nvm use --lts` to use the LTS version of node
6. Type the command `node --version` to check if node is correctly installed.

**Comment by GanyFeta** [comment]
nvm --version 0.37.2

node --version v10.15.2
